# Generated by Django 3.2.3 on 2021-06-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('candidates_count', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('S', 'Selected'), ('R', 'Rejected'), ('J', 'Joined'), ('DNJ', 'Did Not Join'), ('TBD', 'Pending')], default='TBD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pariticipant_one', to='Interviews.participant')),
                ('candidate_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pariticipant_two', to='Interviews.participant')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='Interviews.interview')),
            ],
        ),
    ]
