# Generated by Django 3.2.3 on 2021-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0002_interview_interviewparticipants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=40),
        ),
    ]
