# Generated by Django 3.2.3 on 2021-06-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0003_alter_participant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
