# Generated by Django 3.2.3 on 2021-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0004_participant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
