# Generated by Django 3.2.3 on 2021-06-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interviews', '0005_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewparticipants',
            name='candidate_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pariticipant_one', to='Interviews.participant'),
        ),
        migrations.AlterField(
            model_name='interviewparticipants',
            name='candidate_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pariticipant_two', to='Interviews.participant'),
        ),
    ]
